[package]
name = "nyanfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
indoc = "2.0.0"
nom = "7.1.3"
pretty_assertions = "1.3.0"
